# Generated by Django 4.1.7 on 2023-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_edu_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount_of_users',
        ),
        migrations.AddField(
            model_name='event',
            name='amount_of_clients',
            field=models.IntegerField(default=10, verbose_name=255),
            preserve_default=False,
        ),
    ]
