# Generated by Django 4.1.7 on 2023-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_edu_main_app', '0002_remove_event_amount_of_users_event_amount_of_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount_of_clients',
        ),
        migrations.AddField(
            model_name='event',
            name='amount_of_clients_at_event',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
