# Generated by Django 4.1.7 on 2023-07-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ya_edu_main_app', '0003_remove_event_amount_of_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ya_edu_main_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ya_edu_main_app.user_app')),
            ],
        ),
    ]
