# Generated by Django 4.1.7 on 2023-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_edu_main_app', '0004_eventuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
