# Generated by Django 4.1.7 on 2023-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_edu_main_app', '0005_event_theme_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='status',
            field=models.CharField(default='ds', max_length=50),
            preserve_default=False,
        ),
    ]
